// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlfpajonnkbgccaptayl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZnBham9ubmtiZ2NjYXB0YXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwODIxMDQsImV4cCI6MjA2MjY1ODEwNH0.HCXVSIXIt6DesjBMjjdVyqd7yz8QsEnMD_rzu8dDilc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);